name: Cache Build and Test
run-name: ${{ github.actor }} is testing out cache build(Go) 🚀

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Cache Go Modules and Build Cache
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: go-cache
      #   with:
      #     path: |
      #       ~/.cache/go-build
      #       ~/go/pkg/mod
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      # - name: Set Up Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: 1.23.4

      # - name: Install Dependencies
      #   run: go mod download

      # - name: Build
      #   run: go build -v ./...

      # - name: Test
      #   run: go test -v ./...
      - name: Cache date
        id: cache-date
        uses: actions/cache@v3
        with:
          path: ~/prime-dates
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}
            -${{ hashFiles('**/lockfiles') }}
   
      - name: Echo cache key 
        run: | 
           echo ${{ runner.os }}-${{ steps.get-date.outputs.date }}
            -${{ hashFiles('**/lockfiles') }}
            
        if: steps.cache-date.outputs.cache-hit != 'true'
      - name: Generate Prime Numbers
        run: |
          mkdir -p prime-dates
          echo "Cached content generated on $(date)" > prime-dates/example.txt
      
      - if: ${{ steps.cache-date.outputs.cache-hit == 'true' }}
        name: Check for cache hit
        run: |
          echo "Got cache hit on key"
          cat prime-dates/example.txt
