name: Trigger Reusable Workflow

on:
  push:
    branches:
      - master

jobs:
  invoke_create_issue:
    uses: sachinthapa/learning_gaction/.github/workflows/trigger_reusable_workflow.yml@master
    with:
      title: "Build Failure Detected"
      body: "The build failed during the testing phase. Please investigate."
