name: Trigger Reusable Workflow

on:
  push:
    branches:
      - master

jobs:
  invoke_create_issue:
    permissions:
      issues: write 
    uses: sachinthapa/learning_gaction/.github/workflows/workflow_call_dispatch.yml@master
    with:
      title: "Build Failure Detected"
      body: "The build failed during the testing phase. Please investigate."
